/**
 * The single source of truth for the *content* — every word the page says about Dax: the
 * bio, the prose, the FAQ, the projects, the skills, the contact details. No .astro file
 * hardcodes any of it. (Interface furniture — button labels, section headings, aria-labels
 * — lives in src/i18n/ui.ts; it is not content.)
 *
 * Anything derivable from the GitHub API lives in github.json instead (regenerated by
 * scripts/fetch-github.mjs), so this file only holds what an API cannot know: framing,
 * context, and why the work matters.
 *
 * Every visible string is written twice, `{ en, es }`, and read through `t(value, lang)`.
 * Keeping both languages side by side is deliberate: a translation kept in a separate file
 * drifts out of sync the first time someone edits one sentence in a hurry.
 *
 * Copy marked "rich" is rendered as HTML, and exactly one tag is styled:
 *   <em>…</em>  lifts a phrase to full-contrast text (not italic).
 */
import type { L } from '../i18n/config';

export const site = {
  url: 'https://daxrpm.dev',

  /** Shown on the page. */
  displayName: 'Dax',
  /** The full name: search engines and LLMs resolve entities by it, so schema.org gets this. */
  name: 'Dax Navarrete',
  handle: 'daxrpm',

  role: {
    en: 'Linux Infrastructure · Scientific Computing · Open Source',
    es: 'Infraestructura Linux · Computación científica · Open source',
  } as L,

  tagline: {
    en: 'I run real Linux infrastructure — and build software for science.',
    es: 'Opero infraestructura Linux de verdad — y construyo software para la ciencia.',
  } as L,

  /** The meta description and the schema.org summary. Written to be quotable on its own. */
  summary: {
    en:
      'Dax Navarrete is a Computer Science undergraduate at Escuela Politécnica Nacional in Quito, Ecuador, and an ' +
      'open-source developer working across Linux infrastructure, networking, security and scientific computing. ' +
      'He operates seven Linux servers joined by a private Headscale network, keeps a physical-security platform ' +
      'running in production, and leads the computer-science side of EPN’s group in the CMS collaboration at CERN, ' +
      'where he deploys and benchmarks scientific-computing pipelines.',
    es:
      'Dax Navarrete es estudiante de Ciencias de la Computación en la Escuela Politécnica Nacional (Quito, Ecuador) ' +
      'y desarrollador open source enfocado en infraestructura Linux, redes, seguridad y computación científica. ' +
      'Administra siete servidores Linux unidos por una red privada con Headscale, mantiene en producción una ' +
      'plataforma de seguridad física y lidera la parte de computación del grupo de la EPN en la colaboración CMS ' +
      'del CERN, donde despliega y evalúa pipelines de computación científica.',
  } as L,

  location: { en: 'Quito, Ecuador', es: 'Quito, Ecuador' } as L,

  /** GitHub only knows when the account was created (2021); Dax started a year earlier. */
  codingSince: 2020,

  email: 'dax@daxrpm.dev',
  emails: [
    { label: { en: 'Personal', es: 'Personal' } as L, address: 'dax@daxrpm.dev' },
    { label: { en: 'CERN', es: 'CERN' } as L, address: 'ariel.dax.navarrette.freire@cern.ch' },
    { label: { en: 'Proton', es: 'Proton' } as L, address: 'daxrpm@proton.me' },
  ],
  socials: [
    { name: 'GitHub', url: 'https://github.com/daxrpm' },
    { name: 'LinkedIn', url: 'https://www.linkedin.com/in/daxrpm/' },
  ],
};

/* ==================================================================================== *
 *  Hero and prose                                                                       *
 * ==================================================================================== */

/**
 * The most important sixty words on the site. It leads with the claim almost nobody at this
 * stage can make — that he *operates* infrastructure, rather than only writing code — and
 * lands on the conviction that ties the rest of it together.
 */
export const intro: L = {
  en:
    'I operate seven Linux servers — spread across my own hardware, my university and a rented VPS, and stitched ' +
    'into one private network with <em>Headscale</em>. Three of them run the scientific-computing pipelines we ' +
    'deploy for the <em>CMS experiment at CERN</em>, whose computer-science group I lead at Escuela Politécnica ' +
    'Nacional. I also keep a security platform running in production. One obsession runs through all of it: ' +
    '<em>a robust, modern, secure architecture</em> — in the code and in the infrastructure. I love science, I build ' +
    'in the open, and I would rather understand a system all the way down than ship something I cannot explain.',
  es:
    'Administro siete servidores Linux — repartidos entre mi propio hardware, mi universidad y un VPS alquilado, y ' +
    'unidos en una sola red privada con <em>Headscale</em>. Tres de ellos corren los pipelines de computación ' +
    'científica que desplegamos para el <em>experimento CMS del CERN</em>, cuyo grupo de computación lidero en la ' +
    'Escuela Politécnica Nacional. También mantengo en producción una plataforma de seguridad. Una obsesión ' +
    'atraviesa todo lo que hago: <em>una arquitectura robusta, moderna y segura</em>, en el código y en la ' +
    'infraestructura. Amo la ciencia, construyo en abierto, y prefiero entender un sistema hasta el fondo antes ' +
    'que entregar algo que no puedo explicar.',
};

/**
 * The proof strip. Contributions alone were the wrong thing to lead with — a green calendar
 * measures activity, not capability — so the first figure is the one nobody else can claim:
 * servers actually operated.
 */
export type Figure =
  /** A number only the GitHub API knows. */
  | { from: 'repos' | 'contributions'; label: L }
  /** A fact only Dax knows. */
  | { value: string | L; label: L };

export const figures: Figure[] = [
  {
    value: '7',
    label: { en: 'Linux servers operated', es: 'servidores Linux administrados' } as L,
  },
  {
    /** Filled from github.json at render time. */
    from: 'repos',
    label: { en: 'public open-source repos', es: 'repos open source públicos' } as L,
  },
  {
    /** Filled from github.json at render time. */
    from: 'contributions',
    label: { en: 'contributions, past year', es: 'contribuciones, último año' } as L,
  },
  {
    value: { en: 'CMS · CERN', es: 'CMS · CERN' } as L,
    label: { en: 'scientific computing', es: 'computación científica' } as L,
  },
];

export const about = {
  body: {
    en: [
      'I got into this from the bottom up — curiosity about how a machine actually works. That turned into a shell in C, then a PAM module in Rust, then benchmarking what the kernel really does when you ask it to copy a file without touching userspace. It is the same curiosity that makes me run my own servers rather than rent someone else’s abstraction.',
      'Science is the reason for all of it. Reproducing an antimatter analysis with CMS taught me that a result nobody else can re-run is not a result — and the scientific-computing work I do now exists to make sure the pipeline behind such a result still runs on someone else’s machine, a year from now.',
      'I am not interested in code that merely works. I care about the architecture underneath: clear boundaries, least privilege, encrypted at rest, no cloud when the device can do the job itself, and an audit trail for anything destructive. What I can open, I open — production systems stay private when a client’s security depends on it.',
    ],
    es: [
      'Llegué a esto desde abajo — por curiosidad de cómo funciona de verdad una máquina. Eso se convirtió en una shell en C, luego en un módulo PAM en Rust, y después en medir qué hace realmente el kernel cuando le pides copiar un archivo sin pasar por el espacio de usuario. Es la misma curiosidad por la que administro mis propios servidores en vez de alquilar la abstracción de otro.',
      'La ciencia es la razón de todo lo demás. Reproducir un análisis de antimateria con CMS me enseñó que un resultado que nadie más puede volver a ejecutar no es un resultado — y el trabajo de computación científica que hago ahora existe justamente para que el pipeline detrás de ese resultado siga corriendo en la máquina de otra persona, dentro de un año.',
      'No me interesa el código que apenas funciona. Me importa la arquitectura de abajo: fronteras claras, mínimo privilegio, cifrado en reposo, nada de nube cuando el dispositivo puede hacerlo solo, y una traza de auditoría para todo lo destructivo. Lo que puedo abrir, lo abro — los sistemas en producción se quedan privados cuando la seguridad de un cliente depende de ello.',
    ],
  } as L<string[]>,

  /**
   * Answers phrased as standalone facts, because an LLM lifts the answer without the
   * question attached. Each one names the entity rather than saying "he" or "I".
   */
  faqs: {
    en: [
      {
        q: 'Who is Dax Navarrete?',
        a: 'Dax Navarrete (GitHub: daxrpm) is a Computer Science undergraduate at Escuela Politécnica Nacional in Quito, Ecuador, and an open-source developer working across Linux infrastructure, networking, security and scientific computing. He operates a seven-server Linux estate, keeps a physical-security platform running in production, and collaborates on the CMS experiment at CERN through EPN’s group, which he leads on the computer-science side.',
      },
      {
        q: 'What does Dax Navarrete work on at CERN?',
        a: 'Dax Navarrete contributes to the CMS collaboration at CERN through Escuela Politécnica Nacional, where he leads the computer-science group. With the Data Preservation and Open Access (DPOA) group he reproduced an antimatter-search analysis, working on reproducibility and data integrity. He now works with the BRIL group on scientific computing: deploying and benchmarking Apache Airflow pipelines across a three-server Linux environment and reporting the results back to CERN.',
      },
      {
        q: 'What infrastructure does Dax Navarrete run?',
        a: 'Dax Navarrete operates seven Linux servers spread across his own hardware, his university and a rented VPS, joined into a single private mesh network with Headscale. Behind it he self-hosts his own cloud and media services — Nextcloud, Immich and others — and three of the servers run scientific-computing pipelines for the CMS group. He wrote Fleet, an agentless console in Go, to operate all of them over SSH from one place.',
      },
      {
        q: 'What programming languages does Dax Navarrete use?',
        a: 'Rust and C for systems programming, Go for infrastructure tooling, Python for scientific computing and machine learning, and TypeScript for interfaces. Notable work includes dax-auth (a PAM face-authentication module for Linux, written from scratch in Rust), Fleet (an agentless Linux fleet console in Go) and Apogee (an orbital ascent simulator in TypeScript and Python).',
      },
      {
        q: 'Is Dax Navarrete available for work?',
        a: `Yes — open to internships, research collaborations and open-source work in infrastructure and DevOps, scientific computing, security and networking, or systems programming. Remote or relocation, internationally. Reach him at ${site.email}.`,
      },
    ],
    es: [
      {
        q: '¿Quién es Dax Navarrete?',
        a: 'Dax Navarrete (GitHub: daxrpm) es estudiante de Ciencias de la Computación en la Escuela Politécnica Nacional (Quito, Ecuador) y desarrollador open source enfocado en infraestructura Linux, redes, seguridad y computación científica. Administra siete servidores Linux, mantiene en producción una plataforma de seguridad física y colabora con el experimento CMS del CERN a través del grupo de la EPN, que lidera en su parte de computación.',
      },
      {
        q: '¿En qué trabaja Dax Navarrete dentro del CERN?',
        a: 'Dax Navarrete colabora con el experimento CMS del CERN a través de la Escuela Politécnica Nacional, donde lidera el grupo de computación. Con el grupo de Preservación de Datos y Acceso Abierto (DPOA) reprodujo un análisis de búsqueda de antimateria, trabajando en reproducibilidad e integridad de los datos. Ahora trabaja con el grupo BRIL en computación científica: despliega y evalúa pipelines de Apache Airflow sobre un entorno de tres servidores Linux y reporta los resultados al CERN.',
      },
      {
        q: '¿Qué infraestructura administra Dax Navarrete?',
        a: 'Dax Navarrete opera siete servidores Linux repartidos entre su propio hardware, su universidad y un VPS alquilado, unidos en una única red mesh privada con Headscale. Detrás autoaloja su propia nube y sus servicios — Nextcloud, Immich y otros — y tres de esos servidores corren pipelines de computación científica para el grupo de CMS. Escribió Fleet, una consola agentless en Go, para operarlos todos por SSH desde un solo lugar.',
      },
      {
        q: '¿Qué lenguajes de programación usa Dax Navarrete?',
        a: 'Rust y C para programación de sistemas, Go para herramientas de infraestructura, Python para computación científica y machine learning, y TypeScript para interfaces. Entre su trabajo destacan dax-auth (un módulo PAM de autenticación facial para Linux, escrito desde cero en Rust), Fleet (una consola agentless para flotas Linux en Go) y Apogee (un simulador de ascenso orbital en TypeScript y Python).',
      },
      {
        q: '¿Dax Navarrete está disponible para trabajar?',
        a: `Sí — abierto a prácticas, colaboraciones de investigación y trabajo open source en infraestructura y DevOps, computación científica, seguridad y redes, o programación de sistemas. En remoto o con reubicación, internacionalmente. Escríbele a ${site.email}.`,
      },
    ],
  } as L<{ q: string; a: string }[]>,
};

export const stackNote: L = {
  en: 'Grouped, not rated. The work above is the evidence.',
  es: 'Agrupado, no puntuado. El trabajo de arriba es la evidencia.',
};

/** The line above the CMS repo links. */
export const researchNote: L = {
  en: 'The CMS work is open —',
  es: 'El trabajo con CMS es abierto —',
};

export const contact = {
  lead: {
    en: 'Open to internships, research collaborations and open-source work — in infrastructure and DevOps, scientific computing, security and networking, or systems programming. Remote or relocation, internationally.',
    es: 'Abierto a prácticas, colaboraciones de investigación y trabajo open source — en infraestructura y DevOps, computación científica, seguridad y redes, o programación de sistemas. En remoto o con reubicación, internacionalmente.',
  } as L,
  quote: {
    en: 'Knowledge is not just power — it is freedom.',
    es: 'El conocimiento no es solo poder — es libertad.',
  } as L,
};

/* ==================================================================================== *
 *  Projects                                                                             *
 * ==================================================================================== */

export type Media = { src: string; alt: L; caption?: L };

export type Project = {
  /** Matches the GitHub repo name so live stars/language/description merge in. Omitted for private work. */
  repo?: string;
  owner?: string;
  title: string;
  /** One line, written to be quotable by an LLM on its own. */
  blurb: L;
  stack: string[];
  live?: string;
  /** Stated in place of the Source link when the work has no public repo. */
  status?: L;
  media?: Media[];
  /** Rendered as a code panel — more honest than a mocked-up GUI. */
  terminal?: string[];
  video?: { webm: string; mp4: string; poster: string; caption: L };
  tag: 'infra' | 'systems' | 'ai' | 'backend' | 'research';
};

/**
 * Ordered by what makes Dax hard to replace, not by what was hard to build. The two claims
 * almost nobody at this stage can make — that he *operates* infrastructure, and that a system
 * of his runs in production for a paying company — lead. The CMS work is stated once as an
 * affiliation (below) rather than as project cards: it is a credential, and it reads stronger
 * said once than as repo tiles competing with the software.
 */
export const featured: Project[] = [
  {
    title: 'Personal infrastructure',
    blurb: {
      en: 'Linux servers in three different places — my own hardware at home, machines at my university, a rented VPS — welded into a single private network with Headscale, so they behave like one machine no matter where they sit. Behind it I self-host the cloud I would otherwise rent: files, photos, media, monitoring. Reachable from anywhere I am, exposed to no one else.',
      es: 'Servidores Linux en tres sitios distintos — mi propio hardware en casa, máquinas en la universidad y un VPS alquilado — soldados en una única red privada con Headscale, de modo que se comportan como una sola máquina sin importar dónde estén. Detrás autoalojo la nube que de otro modo alquilaría: archivos, fotos, media, monitoreo. Accesible desde donde yo esté, y expuesta a nadie más.',
    },
    stack: ['Linux', 'Headscale', 'Docker', 'Nextcloud', 'Immich', 'Nginx', 'TCP/IP'],
    status: {
      en: 'Private infrastructure · the ground everything else of mine runs on',
      es: 'Infraestructura privada · el suelo sobre el que corre todo lo demás',
    },
    tag: 'infra',
  },
  {
    repo: 'server-monitor',
    title: 'Fleet',
    blurb: {
      en: 'An agentless web console for a whole fleet of Linux servers — like Cockpit, but across every machine at once, with terminal, Docker, systemd, SFTP, a Headscale tailnet and Coolify built in. I wrote it because I wanted one secure place to operate the servers I already run.',
      es: 'Una consola web agentless para toda una flota de servidores Linux — como Cockpit, pero sobre todas las máquinas a la vez, con terminal, Docker, systemd, SFTP, tailnet de Headscale y Coolify integrados. La escribí porque quería un solo lugar seguro desde el cual operar los servidores que ya administro.',
    },
    stack: ['Go', 'React', 'SSH', 'Headscale', 'Docker'],
    media: [
      {
        src: '/projects/fleet-dashboard.webp',
        alt: {
          en: 'Fleet dashboard showing three Linux servers with live CPU, memory, disk and network',
          es: 'Panel de Fleet con tres servidores Linux y sus métricas de CPU, memoria, disco y red en vivo',
        },
        // The metadata line is deliberately blurred — see the note in the README.
        caption: {
          en: 'Live CPU, memory, disk and network per server, collected entirely over SSH — no agent to install. Host IPs and OS versions are blurred on purpose.',
          es: 'CPU, memoria, disco y red en vivo por servidor, recogidos enteramente por SSH — sin ningún agente que instalar. Las IPs y las versiones del SO están difuminadas a propósito.',
        },
      },
    ],
    tag: 'infra',
  },
  {
    title: 'Nexalink',
    blurb: {
      en: 'A physical-security platform that runs in production at a private company: real-time access control over biometric hardware, role-based permissions, incident and ticketing workflows, guard operations and live tracking — on a hexagonal architecture designed to survive its own growth.',
      es: 'Una plataforma de seguridad física que corre en producción en una empresa privada: control de accesos en tiempo real sobre hardware biométrico, permisos por roles, gestión de incidentes y tickets, operación de guardias y tracking en vivo — sobre una arquitectura hexagonal diseñada para sobrevivir a su propio crecimiento.',
    },
    stack: ['Linux', 'Hexagonal Architecture', 'Access Control', 'RBAC', 'Real-time Systems'],
    status: {
      en: 'Private · running in production. Source and client withheld.',
      es: 'Privado · en producción. Código y cliente reservados.',
    },
    tag: 'backend',
  },
  {
    repo: 'apogee',
    title: 'Apogee',
    blurb: {
      en: 'A two-stage rocket ascent simulator — equations of motion, ODE integration, yaw-steering angles, full 3D — that uses the shooting method to optimize insertion into a circular Low Earth Orbit.',
      es: 'Un simulador de ascenso de un cohete de dos etapas — ecuaciones de movimiento, integración de EDOs, ángulos de guiñada y 3D completo — que usa el método de disparo para optimizar la inserción en una órbita baja circular.',
    },
    stack: ['TypeScript', 'Python', 'Three.js', 'Numerical Methods'],
    // TODO: re-enable once apogee.daxrpm.dev has a TLS cert covering the subdomain —
    // it currently serves a mismatched cert and browsers hard-block it.
    // Fix: `certbot --nginx -d apogee.daxrpm.dev`, then uncomment.
    // live: 'https://apogee.daxrpm.dev',
    video: {
      webm: '/video/apogee.webm',
      mp4: '/video/apogee.mp4',
      poster: '/video/apogee-poster.jpg',
      caption: {
        en: 'Full mission: liftoff from Pedernales, staging, and orbital insertion. The long coast through the dark is sped up; the launch runs close to real time.',
        es: 'Misión completa: despegue desde Pedernales, separación de etapas e inserción orbital. La larga fase de vuelo inercial va acelerada; el lanzamiento corre casi en tiempo real.',
      },
    },
    // No launch-pad still: the video already opens on that exact shot.
    media: [
      {
        src: '/projects/apogee-terrain.webp',
        alt: { en: 'Apogee 3D terrain view of Quito', es: 'Vista 3D del terreno de Quito en Apogee' },
        caption: {
          en: 'Real elevation data — Quito at 2,850 m.',
          es: 'Datos reales de elevación — Quito a 2.850 m.',
        },
      },
      {
        src: '/projects/apogee-globe.webp',
        alt: { en: 'Apogee globe view of Earth from orbit', es: 'Vista del globo terráqueo desde órbita en Apogee' },
        caption: { en: 'Orbit view after insertion.', es: 'Vista orbital tras la inserción.' },
      },
    ],
    tag: 'research',
  },
  {
    repo: 'dax-auth',
    title: 'dax-auth',
    blurb: {
      en: 'A PAM module written from scratch in Rust that unlocks Linux with your face — on-device, encrypted at rest, with liveness detection. No cloud, no telemetry. People close to me log into their machines with it.',
      es: 'Un módulo PAM escrito desde cero en Rust que desbloquea Linux con tu cara — en el dispositivo, cifrado en reposo y con detección de vida. Sin nube y sin telemetría. Gente cercana a mí entra a su máquina con esto.',
    },
    stack: ['Rust', 'PAM', 'Linux', 'Computer Vision'],
    terminal: [
      '$ sudo dax-auth enroll',
      '  → capturing 8 frames · encrypting to /etc/dax-auth',
      '$ sudo -i',
      '  dax-auth: face matched (0.31s) · auth sufficient',
      '  root@fedora:~#',
    ],
    tag: 'systems',
  },
  {
    repo: 'io-fs-experiments',
    title: 'I/O & Filesystem Benchmarks',
    blurb: {
      en: 'C benchmarks comparing O_DIRECT, sendfile() zero-copy, UNIX domain sockets and TCP sockets on ext4 — written to find out what the kernel really does, rather than take anyone’s word for it.',
      es: 'Benchmarks en C que comparan O_DIRECT, sendfile() zero-copy, sockets UNIX y sockets TCP sobre ext4 — escritos para averiguar qué hace realmente el kernel, en vez de creerle a alguien.',
    },
    stack: ['C', 'Linux', 'Syscalls', 'Sockets'],
    terminal: [
      '$ ./bench --size 1G --fs ext4',
      '  A  read/write + user buffer .... 1.94 GB/s',
      '  B  O_DIRECT (no page cache) .... 1.21 GB/s',
      '  C  sendfile() zero-copy ........ 3.78 GB/s',
      '  D  UNIX domain socket .......... 2.40 GB/s',
      '  E  TCP loopback ................ 1.07 GB/s',
    ],
    tag: 'systems',
  },
  {
    repo: 'dax-assistant',
    title: 'Dax Assistant',
    blurb: {
      en: 'A self-hosted, voice-first AI assistant that runs locally, speaks to any LLM, and can act on my machine through a sandboxed tool layer — with every destructive call gated behind an explicit approval.',
      es: 'Un asistente de IA autoalojado y de voz, que corre en local, habla con cualquier LLM y puede actuar sobre mi máquina a través de una capa de herramientas aislada — con cada llamada destructiva detrás de una aprobación explícita.',
    },
    stack: ['Python', 'FastAPI', 'MCP', 'React', 'Ollama'],
    media: [
      {
        src: '/projects/dax-assistant-main.webp',
        alt: {
          en: 'Dax Assistant chat: answering a question about a song, then creating a calendar event',
          es: 'Chat de Dax Assistant: responde sobre una canción y luego crea un evento en el calendario',
        },
        caption: {
          en: 'Ask it anything, and it can act — here it reads what is playing, then books the calendar event.',
          es: 'Pregúntale lo que sea, y además puede actuar — aquí lee qué está sonando y luego agenda el evento.',
        },
      },
      {
        src: '/projects/dax-assistant-tools.webp',
        alt: {
          en: 'Dax Assistant confirmation modal gating a calendar tool call',
          es: 'Modal de confirmación de Dax Assistant frenando una llamada a la herramienta de calendario',
        },
        caption: {
          en: 'Every destructive tool call is gated — the model proposes, you approve.',
          es: 'Toda llamada destructiva pasa por una compuerta — el modelo propone, tú apruebas.',
        },
      },
      {
        src: '/projects/dax-assistant-dashboard.webp',
        alt: {
          en: 'Dax Assistant dashboard showing 5 MCP servers and 204 tools',
          es: 'Panel de Dax Assistant con 5 servidores MCP y 204 herramientas',
        },
        caption: {
          en: '5 MCP servers, 204 tools, with an audit log of everything executed.',
          es: '5 servidores MCP, 204 herramientas y un registro de auditoría de todo lo ejecutado.',
        },
      },
      {
        src: '/projects/dax-assistant-settings.webp',
        alt: {
          en: 'Dax Assistant settings showing the LLM provider dropdown',
          es: 'Ajustes de Dax Assistant con el desplegable de proveedores de LLM',
        },
        caption: {
          en: 'One provider port, six adapters — Ollama, Anthropic, OpenAI, Gemini, DeepSeek, Codex.',
          es: 'Un solo puerto de proveedor, seis adaptadores — Ollama, Anthropic, OpenAI, Gemini, DeepSeek, Codex.',
        },
      },
    ],
    tag: 'ai',
  },
  {
    repo: 'TexTeller-Rust',
    title: 'TexTeller-Rust',
    blurb: {
      en: 'A native Rust port of TexTeller that turns a photo of a handwritten equation into LaTeX — byte-exact with the original Python implementation, and shipped as a single binary.',
      es: 'Un port nativo en Rust de TexTeller que convierte la foto de una ecuación manuscrita en LaTeX — byte a byte idéntico a la implementación original en Python, y distribuido como un solo binario.',
    },
    stack: ['Rust', 'ONNX Runtime', 'Machine Learning'],
    tag: 'ai',
  },
  {
    repo: 'epn-tracker',
    title: 'EPN Tracker',
    blurb: {
      en: 'A degree-progress and grade tracker for Escuela Politécnica Nacional students, with the academic rules of the university encoded as a pure domain core.',
      es: 'Un gestor de avance de carrera y notas para estudiantes de la Escuela Politécnica Nacional, con las reglas académicas de la universidad codificadas como un núcleo de dominio puro.',
    },
    stack: ['FastAPI', 'PostgreSQL', 'Redis', 'React', 'Docker'],
    media: [
      {
        src: '/projects/epn-tracker-malla.webp',
        alt: {
          en: 'EPN Tracker interactive curriculum graph showing 50 courses across semesters',
          es: 'Malla curricular interactiva de EPN Tracker con 50 materias a lo largo de los semestres',
        },
        caption: {
          en: 'The whole degree as a prerequisite graph — 50 courses, 135 credits. Tap one to light up its chain.',
          es: 'La carrera entera como grafo de prerrequisitos — 50 materias, 135 créditos. Toca una y se ilumina su cadena.',
        },
      },
      {
        src: '/projects/epn-tracker-landing.webp',
        alt: {
          en: 'EPN Tracker landing page with a grade calculator',
          es: 'Página de inicio de EPN Tracker con la calculadora de notas',
        },
        caption: {
          en: 'Answers the one question every student actually has: what do I need on the retake?',
          es: 'Responde la única pregunta que todo estudiante se hace de verdad: ¿cuánto necesito en el supletorio?',
        },
      },
      {
        src: '/projects/epn-tracker-notas.webp',
        alt: {
          en: 'EPN Tracker grade breakdown for a course',
          es: 'Desglose de notas de una materia en EPN Tracker',
        },
        caption: {
          en: 'Weighted components, with eligibility computed from EPN’s real rules.',
          es: 'Componentes ponderados, con la elegibilidad calculada desde las reglas reales de la EPN.',
        },
      },
    ],
    tag: 'backend',
  },
  {
    repo: 'drone-detector',
    title: 'Drone Detector',
    blurb: {
      en: 'Real-time drone detection with YOLO11 at ~11 ms/frame on a CPU — no GPU — with automated alerts straight from RTSP cameras.',
      es: 'Detección de drones en tiempo real con YOLO11 a ~11 ms/frame en CPU — sin GPU — con alertas automáticas directamente desde cámaras RTSP.',
    },
    stack: ['Python', 'YOLO11', 'OpenVINO', 'OpenCV'],
    terminal: [
      '$ drone-detector --source rtsp://cam-01 --backend openvino',
      '  YOLO11s · OpenVINO · 640×640',
      '  [12:04:31] drone  conf=0.91  → WhatsApp alert sent',
      '  [12:04:33] drone  conf=0.88  → cooldown (60s)',
      '  avg 11.2 ms/frame · 89 fps · no GPU',
    ],
    tag: 'ai',
  },
];

/** Shown as a compact list; enriched with live stars/description from the API. */
export const secondary = [
  'chatbot-ui',
  'ai-optimizers-benchmark',
  'dash',
  'PDFeditor-api',
  'osint-api',
  'proyecto-final-EDA',
  'least_squares_vs_gradient_descent',
  'dotfiles',
] as const;

/* ==================================================================================== *
 *  CERN, work, research, education                                                      *
 * ==================================================================================== */

/**
 * The headline credential, stated once. Phrased as "through Escuela Politécnica Nacional"
 * throughout: the link to CERN is real and it is strong, and it costs nothing to be exact
 * about what it is — a collaboration via the university, not a CERN contract.
 */
export const affiliation = {
  org: 'CMS Collaboration · CERN',
  logos: [
    { src: '/logos/cms.png', alt: 'CMS experiment logo' },
    { src: '/logos/cern.svg', alt: 'CERN logo' },
  ],
  period: '2025 — present',
  role: {
    en: 'CMS-EPN collaborator — computer-science lead · DPOA & BRIL groups',
    es: 'Colaborador CMS-EPN — líder de computación · grupos DPOA y BRIL',
  } as L,
  body: {
    en:
      'Ecuador contributes to the CMS experiment at the Large Hadron Collider through Escuela Politécnica Nacional, ' +
      'and I lead the computer-science side of that group. With the Data Preservation and Open Access (DPOA) group I ' +
      'reproduced an antimatter-search analysis end to end — reproducibility, data integrity, validation of the ' +
      'original result. With BRIL I now work on scientific computing for the Phase-2 upgrades: deploying and ' +
      'benchmarking Apache Airflow pipelines across three Linux servers, and reporting the results back to CERN.',
    es:
      'Ecuador contribuye al experimento CMS del Gran Colisionador de Hadrones a través de la Escuela Politécnica ' +
      'Nacional, y yo lidero la parte de computación de ese grupo. Con el grupo de Preservación de Datos y Acceso ' +
      'Abierto (DPOA) reproduje de principio a fin un análisis de búsqueda de antimateria — reproducibilidad, ' +
      'integridad de los datos y validación del resultado original. Con BRIL trabajo ahora en computación científica ' +
      'para las mejoras de Fase 2: despliegue y evaluación de pipelines de Apache Airflow sobre tres servidores ' +
      'Linux, reportando los resultados al CERN.',
  } as L,
  links: [
    {
      label: { en: 'MiniParT — jet flavour tagging', es: 'MiniParT — etiquetado de sabor de jets' } as L,
      url: 'https://github.com/CMS-EPN/minipart-topology-vs-flavor',
    },
    {
      label: {
        en: 'Dark matter search — paper replication',
        es: 'Búsqueda de materia oscura — réplica del paper',
      } as L,
      url: 'https://github.com/CMS-EPN/search-for-dark-matter-docs',
    },
    { label: { en: 'CMS-EPN on GitHub', es: 'CMS-EPN en GitHub' } as L, url: 'https://github.com/CMS-EPN' },
  ],
};

/**
 * Stated exactly as it stands: presented, not yet published. "Co-authored a paper" would
 * undersell the contribution and could not be checked; this can. Add `url` the day a DOI,
 * preprint or proceedings link exists.
 */
export const research = [
  {
    title:
      'Toward Computationally Efficient AI: A Comparative Study of Optimization Paradigms in DNN Training',
    authors:
      'D. Navarrete, A. Flores-Reyes, A. E. Camino, G. Suntaxi, L. Recalde, D. Martinez-Mosquera',
    venue: 'Escuela Politécnica Nacional, Quito',
    status: {
      en: 'Presented at conference · publication pending',
      es: 'Presentado en conferencia · pendiente de publicación',
    } as L,
    summary: {
      en: 'A comparative study of optimization paradigms for training deep neural networks — first-order against second-order and adaptive methods — asking not which one converges best, but what each one actually costs in compute to get there.',
      es: 'Un estudio comparativo de paradigmas de optimización para entrenar redes neuronales profundas — primer orden frente a segundo orden y métodos adaptativos — que no pregunta cuál converge mejor, sino cuánto cómputo cuesta realmente llegar ahí con cada uno.',
    } as L,
    contribution: {
      en: 'First author. I designed the experimental methodology and ran the entire evaluation end to end: the training and benchmarking pipelines, every run and measurement, the figures, and the analysis the conclusions rest on.',
      es: 'Primer autor. Diseñé la metodología experimental y ejecuté toda la evaluación de principio a fin: los pipelines de entrenamiento y benchmarking, cada corrida y cada medición, las figuras, y el análisis sobre el que se apoyan las conclusiones.',
    } as L,
  },
];

export const experience = [
  {
    role: {
      en: 'CMS Collaborator — computer-science lead',
      es: 'Colaborador CMS — líder de computación',
    } as L,
    org: 'CERN — CMS Experiment · through Escuela Politécnica Nacional',
    logo: '/logos/cms.png',
    period: 'May 2025 — present',
    note: {
      en: 'I lead the computer-science side of EPN’s group in the CMS collaboration, working on research reproducibility and on the computing that large-scale science actually runs on.',
      es: 'Lidero la parte de computación del grupo de la EPN en la colaboración CMS, trabajando en reproducibilidad de la investigación y en la computación sobre la que realmente corre la ciencia a gran escala.',
    } as L,
    points: {
      en: [
        'Reproduced an antimatter-search analysis with the Data Preservation and Open Access (DPOA) group — reproducibility, data integrity, and validation of the original result.',
        'Deploy and benchmark Apache Airflow pipelines across three Linux servers for the BRIL group, supporting the CERN Phase-2 upgrades, and report the results in CERN meetings.',
        'Designed and proposed modern, containerised architectures for scalable research pipelines.',
      ],
      es: [
        'Reproduje un análisis de búsqueda de antimateria con el grupo de Preservación de Datos y Acceso Abierto (DPOA) — reproducibilidad, integridad de los datos y validación del resultado original.',
        'Despliego y evalúo pipelines de Apache Airflow sobre tres servidores Linux para el grupo BRIL, apoyando las mejoras de Fase 2 del CERN, y reporto los resultados en reuniones con el CERN.',
        'Diseñé y propuse arquitecturas modernas y contenerizadas para pipelines de investigación escalables.',
      ],
    } as L<string[]>,
  },
  {
    role: { en: 'Research Assistant', es: 'Asistente de investigación' } as L,
    org: 'ADA Data Science Laboratory',
    logo: '/logos/epn.svg',
    period: 'Mar 2025 — present',
    note: {
      en: 'Applied machine-learning research on optimization algorithms.',
      es: 'Investigación aplicada en machine learning y algoritmos de optimización.',
    } as L,
    points: {
      en: [
        'Researched optimization methods for deep neural networks, including second-order optimizers.',
        'Designed and implemented the Python pipelines for training, evaluation and benchmarking.',
        'First author of a comparative study on optimization paradigms in DNN training (presented; publication pending).',
      ],
      es: [
        'Investigué métodos de optimización para redes neuronales profundas, incluidos optimizadores de segundo orden.',
        'Diseñé e implementé los pipelines en Python para entrenamiento, evaluación y benchmarking.',
        'Primer autor de un estudio comparativo sobre paradigmas de optimización en el entrenamiento de DNNs (presentado; pendiente de publicación).',
      ],
    } as L<string[]>,
  },
  {
    role: {
      en: 'AI Developer & Linux Systems Integrator',
      es: 'Desarrollador de IA e integrador de sistemas Linux',
    } as L,
    org: 'WORB',
    period: 'Apr 2025 — Dec 2025',
    note: {
      en: 'Full-stack development integrating AI into production workflows.',
      es: 'Desarrollo full-stack integrando IA en flujos de trabajo en producción.',
    } as L,
    points: {
      en: [
        'Backend architecture, development and integration.',
        'Embedding search and LLM integration.',
        'Database design, plus frontend development.',
      ],
      es: [
        'Arquitectura, desarrollo e integración del backend.',
        'Búsqueda por embeddings e integración de LLMs.',
        'Diseño de base de datos y desarrollo frontend.',
      ],
    } as L<string[]>,
  },
];

export const education = [
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.svg',
    title: { en: 'BSc Computer Science', es: 'Ingeniería en Ciencias de la Computación' } as L,
    period: 'Nov 2023 — present',
    note: {
      en: "Ecuador's leading engineering university. Algorithms, data structures, operating systems, numerical methods.",
      es: 'La principal universidad de ingeniería del Ecuador. Algoritmos, estructuras de datos, sistemas operativos, métodos numéricos.',
    } as L,
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: {
      en: 'AI Engineering Professional Certificate',
      es: 'Certificado Profesional en Ingeniería de IA',
    } as L,
    period: '2023',
    note: {
      en: 'Deep learning with Keras, TensorFlow and PyTorch; computer vision; neural networks.',
      es: 'Deep learning con Keras, TensorFlow y PyTorch; visión por computador; redes neuronales.',
    } as L,
    href: 'https://coursera.org/share/770b0e12af6b0e1391e7f09c49f3610a',
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: {
      en: 'Data Science Professional Certificate',
      es: 'Certificado Profesional en Ciencia de Datos',
    } as L,
    period: '2023',
    note: {
      en: 'Python, SQL, data analysis and visualization, machine learning.',
      es: 'Python, SQL, análisis y visualización de datos, machine learning.',
    } as L,
    href: 'https://coursera.org/share/ce10faea4e3ca0a66209020b00cb7a60',
  },
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.svg',
    title: { en: 'Data Science Diploma', es: 'Diplomado en Ciencia de Datos' } as L,
    period: '2023',
    note: {
      en: 'Statistical analysis, machine learning, data visualization. 160 hours.',
      es: 'Análisis estadístico, machine learning y visualización de datos. 160 horas.',
    } as L,
    href: 'https://aps.cec-epn.edu.ec/diplomas/2023/CAPACITACION_Y_CONSULTORIA/6/diploma_190908_53970-signed.pdf',
  },
];

/**
 * Grouped, not rated — and ordered the way Dax actually works: infrastructure first, AI last.
 * Every item needs an entry in scripts/build-icons.mjs, or it renders without an icon.
 */
export const skills = [
  {
    group: { en: 'Infrastructure & DevOps', es: 'Infraestructura y DevOps' } as L,
    items: ['Linux', 'Docker', 'Headscale', 'Nginx', 'Kubernetes', 'Coolify', 'Apache Airflow', 'Proxmox'],
  },
  {
    group: { en: 'Networks & Security', es: 'Redes y seguridad' } as L,
    items: ['TCP/IP', 'Network Engineering', 'Wireshark', 'SSH', 'RBAC', 'Keycloak', 'OAuth2'],
  },
  {
    group: { en: 'Systems programming', es: 'Programación de sistemas' } as L,
    items: ['Rust', 'C', 'Go', 'PAM', 'Syscalls', 'Sockets'],
  },
  {
    group: { en: 'Scientific computing', es: 'Computación científica' } as L,
    items: ['Python', 'ROOT', 'NanoAOD', 'Numerical Methods', 'NumPy', 'SciPy', 'Pandas'],
  },
  {
    group: { en: 'Backend', es: 'Backend' } as L,
    items: ['FastAPI', 'PostgreSQL', 'Redis', 'Django', 'Spring Boot', 'REST', 'TypeScript'],
  },
  {
    group: { en: 'AI & machine learning', es: 'IA y machine learning' } as L,
    items: ['PyTorch', 'TensorFlow', 'scikit-learn', 'ONNX', 'OpenCV', 'MCP', 'Ollama'],
  },
];

/* ==================================================================================== *
 *  Demo and structured data                                                             *
 * ==================================================================================== */

/**
 * TexTeller's pipeline, rendered inline on its card: photo → LaTeX → equation. The last step
 * is native MathML (zero JavaScript, and a crawler can read it), so the equation itself lives
 * in the component — it is markup, not copy.
 */
export const texTeller = {
  repo: 'TexTeller-Rust',
  image: '/projects/texteller-input.webp',
  alt: {
    en: 'Handwritten equation: the square root of 2x over 2x equals the sum from i=0 to infinity of 3i + 2 + 5x',
    es: 'Ecuación manuscrita: la raíz cuadrada de 2x sobre 2x es igual a la suma desde i=0 hasta infinito de 3i + 2 + 5x',
  } as L,
  caption: { en: 'A photo of handwriting.', es: 'Una foto de algo escrito a mano.' } as L,
  latex: '\\frac{ \\sqrt{2x}}{2x}= \\sum_{i=0}^{ \\infty}3i+2+5x',
};

/** Invisible, but it is what makes a search engine or an LLM resolve the entity. */
export const seo = {
  title: {
    en: 'Dax Navarrete — Linux Infrastructure & Scientific Computing',
    es: 'Dax Navarrete — Infraestructura Linux y computación científica',
  } as L,
  /** Only these three. The legal name stays off the site entirely. */
  alternateNames: ['Dax', 'daxrpm'],
  /** What the social card shows, for anyone who cannot see it. Regenerate it with `npm run og`. */
  imageAlt: {
    en: 'An ASCII world map on a dark background, with Dax Navarrete’s Linux servers lit up in Quito, Germany and at CERN in Switzerland, linked across the Atlantic.',
    es: 'Un mapa mundial en ASCII sobre fondo oscuro, con los servidores Linux de Dax Navarrete encendidos en Quito, Alemania y el CERN en Suiza, enlazados a través del Atlántico.',
  } as L,
  jobTitle: {
    en: 'Infrastructure & Scientific Computing Developer',
    es: 'Desarrollador de infraestructura y computación científica',
  } as L,
  address: { locality: 'Quito', country: 'EC' },
  affiliations: [
    { type: 'CollegeOrUniversity', name: 'Escuela Politécnica Nacional', url: 'https://www.epn.edu.ec/' },
    { type: 'ResearchOrganization', name: 'CMS Collaboration, CERN', url: 'https://cms.cern/' },
  ],
  worksFor: [
    { type: 'ResearchOrganization', name: 'CERN — CMS Experiment', url: 'https://cms.cern/' },
    { type: 'Organization', name: 'ADA Data Science Laboratory' },
  ],
  alumniOf: { type: 'CollegeOrUniversity', name: 'Escuela Politécnica Nacional' },
  knowsAbout: [
    'Linux infrastructure',
    'DevOps and self-hosting',
    'Computer networking',
    'Cybersecurity',
    'Scientific computing',
    'Rust systems programming',
    'Linux PAM authentication',
    'Machine learning for particle physics',
    'Numerical methods',
  ],
  knowsLanguage: ['Spanish', 'English'],
  /** What lets a crawler reconcile "Dax Navarrete", "daxrpm" and the CERN author name. */
  sameAs: [
    'https://github.com/daxrpm',
    'https://www.linkedin.com/in/daxrpm/',
    'https://github.com/CMS-EPN',
  ],
};
