/**
 * Hand-curated content. Anything derivable from the GitHub API lives in github.json
 * (regenerated by scripts/fetch-github.mjs), so this file only holds what an API cannot
 * know: framing, context, and why the work matters.
 */

export const site = {
  url: 'https://daxrpm.dev',
  name: 'Dax Navarrete',
  handle: 'daxrpm',
  role: 'Computer Science undergraduate · CMS (CERN) collaborator',
  tagline: 'I build systems software and machine learning for particle physics.',
  summary:
    'Computer Science undergraduate at Escuela Politécnica Nacional in Quito, Ecuador. ' +
    'I work on machine learning for particle physics with the CMS collaboration at CERN, ' +
    'and I write systems software in Rust and C — a PAM face-authentication module for Linux, ' +
    'a shell, and zero-copy I/O benchmarks. Strong interests in network engineering and security.',
  location: 'Quito, Ecuador',
  email: 'dax@daxrpm.dev',
  emails: [
    { label: 'Personal', address: 'dax@daxrpm.dev' },
    { label: 'CERN', address: 'ariel.dax.navarrette.freire@cern.ch' },
    { label: 'Proton', address: 'daxrpm@proton.me' },
  ],
  socials: [
    { name: 'GitHub', url: 'https://github.com/daxrpm' },
    { name: 'LinkedIn', url: 'https://www.linkedin.com/in/dax-navarrete-b07b3826a/' },
  ],
} as const;

export type Media = { src: string; alt: string; caption?: string };

export type Project = {
  /** Matches the GitHub repo name so live stars/language/description merge in. */
  repo: string;
  owner?: string;
  title: string;
  /** One line, written to be quotable by an LLM on its own. */
  blurb: string;
  stack: string[];
  live?: string;
  /** Screenshots, shown as a gallery. */
  media?: Media[];
  /** Rendered as a code panel — more honest than a mocked-up GUI. */
  terminal?: string[];
  video?: { webm: string; mp4: string; poster: string; caption: string };
  tag: 'systems' | 'ai' | 'backend' | 'research';
};

/**
 * The CMS/CERN work is surfaced as an affiliation (see `affiliation` below) rather than
 * as the first two project cards — it is a credential, and it reads stronger stated once
 * than as two repo tiles competing with the software.
 */
export const featured: Project[] = [
  {
    repo: 'apogee',
    title: 'Apogee',
    blurb:
      'A two-stage rocket ascent simulator that uses the shooting method to optimize insertion into a circular Low Earth Orbit.',
    stack: ['TypeScript', 'Python', 'Three.js', 'Numerical Methods'],
    // TODO: re-enable once apogee.daxrpm.dev has a TLS cert covering the subdomain —
    // it currently serves a mismatched cert and browsers hard-block it.
    // Fix: `certbot --nginx -d apogee.daxrpm.dev`, then uncomment.
    // live: 'https://apogee.daxrpm.dev',
    video: {
      webm: '/video/apogee.webm',
      mp4: '/video/apogee.mp4',
      poster: '/video/apogee-poster.jpg',
      caption: 'Full mission, 8× speed: liftoff from Pedernales, staging, and orbital insertion.',
    },
    media: [
      { src: '/projects/apogee-launch.webp', alt: 'Apogee launch control panel with a rocket on the pad', caption: 'Launch control — target altitude and payload mass drive the trajectory solve.' },
      { src: '/projects/apogee-terrain.webp', alt: 'Apogee 3D terrain view of Quito', caption: 'Real elevation data — Quito at 2,850 m.' },
      { src: '/projects/apogee-globe.webp', alt: 'Apogee globe view of Earth from orbit', caption: 'Orbit view after insertion.' },
    ],
    tag: 'research',
  },
  {
    repo: 'dax-auth',
    title: 'dax-auth',
    blurb:
      'A PAM module written from scratch in Rust that unlocks Linux with your face — on-device, encrypted, no cloud, no telemetry.',
    stack: ['Rust', 'PAM', 'Linux', 'Computer Vision'],
    terminal: [
      '$ sudo dax-auth enroll',
      '  → capturing 8 frames · encrypting to /etc/dax-auth',
      '$ sudo -i',
      '  dax-auth: face matched (0.31s) · auth sufficient',
      '  root@fedora:~#',
    ],
    tag: 'systems',
  },
  {
    repo: 'dax-assistant',
    title: 'Dax Assistant',
    blurb:
      'A self-hosted, voice-first AI assistant that runs locally, speaks to any LLM, and can act on your machine through a sandboxed tool layer.',
    stack: ['Python', 'FastAPI', 'MCP', 'React', 'Ollama'],
    media: [
      { src: '/projects/dax-assistant-tools.webp', alt: 'Dax Assistant confirmation modal gating a calendar tool call', caption: 'Every destructive tool call is gated — the model proposes, you approve.' },
      { src: '/projects/dax-assistant-dashboard.webp', alt: 'Dax Assistant dashboard showing 5 MCP servers and 204 tools', caption: '5 MCP servers, 204 tools, with an audit log of everything executed.' },
      { src: '/projects/dax-assistant-settings.webp', alt: 'Dax Assistant settings showing the LLM provider dropdown', caption: 'One provider port, six adapters — Ollama, Anthropic, OpenAI, Gemini, DeepSeek, Codex.' },
      { src: '/projects/dax-assistant-chat.webp', alt: 'Dax Assistant chat answering a question and creating a calendar event', caption: 'Voice or text, with memory across sessions.' },
    ],
    tag: 'ai',
  },
  {
    repo: 'TexTeller-Rust',
    title: 'TexTeller-Rust',
    blurb:
      'A native Rust port of TexTeller that turns a photo of a handwritten equation into LaTeX, byte-exact with the original Python implementation.',
    stack: ['Rust', 'ONNX Runtime', 'Machine Learning'],
    tag: 'ai',
  },
  {
    repo: 'epn-tracker',
    title: 'EPN Tracker',
    blurb:
      'A degree-progress and grade tracker for Escuela Politécnica Nacional students, with the academic rules of the university encoded as a pure domain core.',
    stack: ['FastAPI', 'PostgreSQL', 'Redis', 'React', 'Docker'],
    media: [
      { src: '/projects/epn-tracker-landing.webp', alt: 'EPN Tracker landing page with a grade calculator', caption: 'Answers the one question every student has: what do I need on the retake?' },
      { src: '/projects/epn-tracker-malla.webp', alt: 'EPN Tracker interactive curriculum graph', caption: 'The full curriculum as a prerequisite graph — tap a course to light up its chain.' },
      { src: '/projects/epn-tracker-notas.webp', alt: 'EPN Tracker grade breakdown for a course', caption: 'Weighted components, with eligibility computed from EPN’s real rules.' },
    ],
    tag: 'backend',
  },
  {
    repo: 'drone-detector',
    title: 'Drone Detector',
    blurb:
      'Real-time drone detection with YOLO11 at ~11 ms/frame on a CPU, with automated WhatsApp alerts from RTSP cameras.',
    stack: ['Python', 'YOLO11', 'OpenVINO', 'OpenCV'],
    terminal: [
      '$ drone-detector --source rtsp://cam-01 --backend openvino',
      '  YOLO11s · OpenVINO · 640×640',
      '  [12:04:31] drone  conf=0.91  → WhatsApp alert sent',
      '  [12:04:33] drone  conf=0.88  → cooldown (60s)',
      '  avg 11.2 ms/frame · 89 fps · no GPU',
    ],
    tag: 'ai',
  },
  {
    repo: 'io-fs-experiments',
    title: 'I/O & Filesystem Benchmarks',
    blurb:
      'C benchmarks comparing O_DIRECT, sendfile() zero-copy, UNIX domain sockets and TCP sockets on ext4.',
    stack: ['C', 'Linux', 'Syscalls', 'Sockets'],
    terminal: [
      '$ ./bench --size 1G --fs ext4',
      '  A  read/write + user buffer .... 1.94 GB/s',
      '  B  O_DIRECT (no page cache) .... 1.21 GB/s',
      '  C  sendfile() zero-copy ........ 3.78 GB/s',
      '  D  UNIX domain socket .......... 2.40 GB/s',
      '  E  TCP loopback ................ 1.07 GB/s',
    ],
    tag: 'systems',
  },
];

/** Shown as a compact list; enriched with live stars/description from the API. */
export const secondary = [
  'chatbot-ui',
  'ai-optimizers-benchmark',
  'dash',
  'PDFeditor-api',
  'osint-api',
  'proyecto-final-EDA',
  'least_squares_vs_gradient_descent',
  'dotfiles',
] as const;

/** The headline credential. Stated once, prominently, near the top of the page. */
export const affiliation = {
  org: 'CMS Collaboration · CERN',
  logos: [
    { src: '/logos/cms.png', alt: 'CMS experiment logo' },
    { src: '/logos/cern.svg', alt: 'CERN logo' },
  ],
  period: '2025 — present',
  role: 'Research collaborator — DPOA & BRIL groups, via Escuela Politécnica Nacional',
  body:
    'I work on machine learning for particle physics with the CMS experiment at the Large Hadron Collider, ' +
    'through the EPN group. Two lines of work: a compact ParticleTransformer-inspired classifier (MiniParT) ' +
    'that separates H→bb, H→cc and QCD multijet events on CMS Open Data, and a replication of the CMS search ' +
    'for dark matter produced in association with a top quark at √s = 13 TeV.',
  links: [
    { label: 'MiniParT — jet flavour tagging', url: 'https://github.com/CMS-EPN/minipart-topology-vs-flavor' },
    { label: 'Dark matter search — paper replication', url: 'https://github.com/CMS-EPN/search-for-dark-matter-docs' },
    { label: 'CMS-EPN on GitHub', url: 'https://github.com/CMS-EPN' },
  ],
};

export const education = [
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.png',
    title: 'BSc Computer Science',
    period: '2023 — 2028',
    note: "Ecuador's leading engineering university. Algorithms, data structures, operating systems, numerical methods.",
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: 'AI Engineering Professional Certificate',
    period: '2023',
    note: 'Deep learning with Keras, TensorFlow and PyTorch; computer vision; neural networks.',
    href: 'https://coursera.org/share/770b0e12af6b0e1391e7f09c49f3610a',
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: 'Data Science Professional Certificate',
    period: '2023',
    note: 'Python, SQL, data analysis and visualization, machine learning.',
    href: 'https://coursera.org/share/ce10faea4e3ca0a66209020b00cb7a60',
  },
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.png',
    title: 'Data Science Diploma',
    period: '2023',
    note: 'Statistical analysis, machine learning, data visualization.',
    href: 'https://aps.cec-epn.edu.ec/diplomas/2023/CAPACITACION_Y_CONSULTORIA/6/diploma_190908_53970-signed.pdf',
  },
];

/**
 * Professional experience. EMPTY ON PURPOSE — LinkedIn blocks automated reads (HTTP 999),
 * so nothing here can be filled in without Dax supplying it. The Experience section does
 * not render while this is empty; it is better to omit the section than to invent roles,
 * which is exactly what the previous site did.
 */
export const experience: {
  role: string;
  org: string;
  period: string;
  note: string;
}[] = [];

/**
 * Grouped, not rated. Self-assigned 1–5 levels invite an argument you cannot win and tell
 * a reader nothing the projects don't already prove.
 */
export const skills = [
  { group: 'Languages', items: ['Python', 'Rust', 'C', 'C++', 'Java', 'TypeScript', 'Bash', 'SQL'] },
  { group: 'Systems & Linux', items: ['Linux', 'PAM', 'Syscalls', 'Sockets', 'Docker', 'Nginx', 'Kubernetes'] },
  { group: 'Networks & Security', items: ['TCP/IP', 'Network Engineering', 'Wireshark', 'Keycloak', 'OAuth2'] },
  { group: 'ML & Data', items: ['PyTorch', 'TensorFlow', 'scikit-learn', 'ONNX', 'OpenCV', 'NumPy', 'Pandas'] },
  { group: 'Backend', items: ['FastAPI', 'Django', 'Spring Boot', 'PostgreSQL', 'Redis', 'REST'] },
  { group: 'Physics & Numerics', items: ['ROOT', 'NanoAOD', 'Numerical Methods', 'SciPy', 'Manim'] },
];
