/**
 * Hand-curated content. Anything derivable from the GitHub API lives in github.json
 * (regenerated by scripts/fetch-github.mjs), so this file only holds what an API cannot
 * know: framing, context, and why the work matters.
 */

export const site = {
  url: 'https://daxrpm.dev',
  /** Shown on the page. */
  displayName: 'Dax',
  /** Kept for schema.org and meta: search engines and LLMs resolve entities by full name. */
  name: 'Dax Navarrete',
  handle: 'daxrpm',
  role: 'Computer Science undergraduate · CMS (CERN) collaborator',
  tagline: 'I build systems software and machine learning for particle physics.',
  summary:
    'Computer Science undergraduate at Escuela Politécnica Nacional in Quito, Ecuador. ' +
    'I work on machine learning for particle physics with the CMS collaboration at CERN, ' +
    'and I write systems software in Rust and C — a PAM face-authentication module for Linux, ' +
    'a shell, and zero-copy I/O benchmarks. Strong interests in network engineering and security.',
  location: 'Quito, Ecuador',
  email: 'dax@daxrpm.dev',
  emails: [
    { label: 'Personal', address: 'dax@daxrpm.dev' },
    { label: 'CERN', address: 'ariel.dax.navarrette.freire@cern.ch' },
    { label: 'Proton', address: 'daxrpm@proton.me' },
  ],
  socials: [
    { name: 'GitHub', url: 'https://github.com/daxrpm' },
    { name: 'LinkedIn', url: 'https://www.linkedin.com/in/dax-navarrete-b07b3826a/' },
  ],
} as const;

export type Media = { src: string; alt: string; caption?: string };

export type Project = {
  /** Matches the GitHub repo name so live stars/language/description merge in. */
  repo: string;
  owner?: string;
  title: string;
  /** One line, written to be quotable by an LLM on its own. */
  blurb: string;
  stack: string[];
  live?: string;
  /** Screenshots, shown as a gallery. */
  media?: Media[];
  /** Rendered as a code panel — more honest than a mocked-up GUI. */
  terminal?: string[];
  video?: { webm: string; mp4: string; poster: string; caption: string };
  tag: 'systems' | 'ai' | 'backend' | 'research';
};

/**
 * The CMS/CERN work is surfaced as an affiliation (see `affiliation` below) rather than
 * as the first two project cards — it is a credential, and it reads stronger stated once
 * than as two repo tiles competing with the software.
 */
export const featured: Project[] = [
  {
    repo: 'apogee',
    title: 'Apogee',
    blurb:
      'A two-stage rocket ascent simulator that uses the shooting method to optimize insertion into a circular Low Earth Orbit.',
    stack: ['TypeScript', 'Python', 'Three.js', 'Numerical Methods'],
    // TODO: re-enable once apogee.daxrpm.dev has a TLS cert covering the subdomain —
    // it currently serves a mismatched cert and browsers hard-block it.
    // Fix: `certbot --nginx -d apogee.daxrpm.dev`, then uncomment.
    // live: 'https://apogee.daxrpm.dev',
    video: {
      webm: '/video/apogee.webm',
      mp4: '/video/apogee.mp4',
      poster: '/video/apogee-poster.jpg',
      caption:
        'Full mission: liftoff from Pedernales, staging, and orbital insertion. The long coast through the dark is sped up; the launch runs close to real time.',
    },
    media: [
      { src: '/projects/apogee-launch.webp', alt: 'Apogee launch control panel with a rocket on the pad', caption: 'Launch control — target altitude and payload mass drive the trajectory solve.' },
      { src: '/projects/apogee-terrain.webp', alt: 'Apogee 3D terrain view of Quito', caption: 'Real elevation data — Quito at 2,850 m.' },
      { src: '/projects/apogee-globe.webp', alt: 'Apogee globe view of Earth from orbit', caption: 'Orbit view after insertion.' },
    ],
    tag: 'research',
  },
  {
    repo: 'dax-auth',
    title: 'dax-auth',
    blurb:
      'A PAM module written from scratch in Rust that unlocks Linux with your face — on-device, encrypted, no cloud, no telemetry.',
    stack: ['Rust', 'PAM', 'Linux', 'Computer Vision'],
    terminal: [
      '$ sudo dax-auth enroll',
      '  → capturing 8 frames · encrypting to /etc/dax-auth',
      '$ sudo -i',
      '  dax-auth: face matched (0.31s) · auth sufficient',
      '  root@fedora:~#',
    ],
    tag: 'systems',
  },
  {
    repo: 'dax-assistant',
    title: 'Dax Assistant',
    blurb:
      'A self-hosted, voice-first AI assistant that runs locally, speaks to any LLM, and can act on your machine through a sandboxed tool layer.',
    stack: ['Python', 'FastAPI', 'MCP', 'React', 'Ollama'],
    media: [
      { src: '/projects/dax-assistant-main.webp', alt: 'Dax Assistant chat: answering a question about a song, then creating a calendar event', caption: 'Ask it anything, and it can act — here it reads what is playing, then books the calendar event.' },
      { src: '/projects/dax-assistant-tools.webp', alt: 'Dax Assistant confirmation modal gating a calendar tool call', caption: 'Every destructive tool call is gated — the model proposes, you approve.' },
      { src: '/projects/dax-assistant-dashboard.webp', alt: 'Dax Assistant dashboard showing 5 MCP servers and 204 tools', caption: '5 MCP servers, 204 tools, with an audit log of everything executed.' },
      { src: '/projects/dax-assistant-settings.webp', alt: 'Dax Assistant settings showing the LLM provider dropdown', caption: 'One provider port, six adapters — Ollama, Anthropic, OpenAI, Gemini, DeepSeek, Codex.' },
    ],
    tag: 'ai',
  },
  {
    repo: 'TexTeller-Rust',
    title: 'TexTeller-Rust',
    blurb:
      'A native Rust port of TexTeller that turns a photo of a handwritten equation into LaTeX, byte-exact with the original Python implementation.',
    stack: ['Rust', 'ONNX Runtime', 'Machine Learning'],
    tag: 'ai',
  },
  {
    repo: 'epn-tracker',
    title: 'EPN Tracker',
    blurb:
      'A degree-progress and grade tracker for Escuela Politécnica Nacional students, with the academic rules of the university encoded as a pure domain core.',
    stack: ['FastAPI', 'PostgreSQL', 'Redis', 'React', 'Docker'],
    media: [
      { src: '/projects/epn-tracker-malla.webp', alt: 'EPN Tracker interactive curriculum graph showing 50 courses across semesters', caption: 'The whole degree as a prerequisite graph — 50 courses, 135 credits. Tap one to light up its chain.' },
      { src: '/projects/epn-tracker-landing.webp', alt: 'EPN Tracker landing page with a grade calculator', caption: 'Answers the one question every student actually has: what do I need on the retake?' },
      { src: '/projects/epn-tracker-notas.webp', alt: 'EPN Tracker grade breakdown for a course', caption: 'Weighted components, with eligibility computed from EPN’s real rules.' },
    ],
    tag: 'backend',
  },
  {
    repo: 'server-monitor',
    title: 'Fleet',
    blurb:
      'An agentless web console for a whole fleet of Linux servers — like Cockpit, but across every machine, with Headscale tailnet and Coolify built in.',
    stack: ['Go', 'React', 'SSH', 'Headscale', 'Docker'],
    media: [
      {
        src: '/projects/fleet-dashboard.webp',
        alt: 'Fleet dashboard showing three Linux servers with live CPU, memory, disk and network',
        // The metadata line is deliberately blurred — see the note in the README.
        caption:
          'Live CPU, memory, disk and network per server, collected entirely over SSH — no agent to install. Host IPs and OS versions are blurred on purpose.',
      },
    ],
    tag: 'systems',
  },
  {
    repo: 'drone-detector',
    title: 'Drone Detector',
    blurb:
      'Real-time drone detection with YOLO11 at ~11 ms/frame on a CPU, with automated WhatsApp alerts from RTSP cameras.',
    stack: ['Python', 'YOLO11', 'OpenVINO', 'OpenCV'],
    terminal: [
      '$ drone-detector --source rtsp://cam-01 --backend openvino',
      '  YOLO11s · OpenVINO · 640×640',
      '  [12:04:31] drone  conf=0.91  → WhatsApp alert sent',
      '  [12:04:33] drone  conf=0.88  → cooldown (60s)',
      '  avg 11.2 ms/frame · 89 fps · no GPU',
    ],
    tag: 'ai',
  },
  {
    repo: 'io-fs-experiments',
    title: 'I/O & Filesystem Benchmarks',
    blurb:
      'C benchmarks comparing O_DIRECT, sendfile() zero-copy, UNIX domain sockets and TCP sockets on ext4.',
    stack: ['C', 'Linux', 'Syscalls', 'Sockets'],
    terminal: [
      '$ ./bench --size 1G --fs ext4',
      '  A  read/write + user buffer .... 1.94 GB/s',
      '  B  O_DIRECT (no page cache) .... 1.21 GB/s',
      '  C  sendfile() zero-copy ........ 3.78 GB/s',
      '  D  UNIX domain socket .......... 2.40 GB/s',
      '  E  TCP loopback ................ 1.07 GB/s',
    ],
    tag: 'systems',
  },
];

/** Shown as a compact list; enriched with live stars/description from the API. */
export const secondary = [
  'chatbot-ui',
  'ai-optimizers-benchmark',
  'dash',
  'PDFeditor-api',
  'osint-api',
  'proyecto-final-EDA',
  'least_squares_vs_gradient_descent',
  'dotfiles',
] as const;

/** The headline credential. Stated once, prominently, near the top of the page. */
export const affiliation = {
  org: 'CMS Collaboration · CERN',
  logos: [
    { src: '/logos/cms.png', alt: 'CMS experiment logo' },
    { src: '/logos/cern.svg', alt: 'CERN logo' },
  ],
  period: '2025 — present',
  role: 'Research collaborator — DPOA & BRIL groups, via Escuela Politécnica Nacional',
  body:
    'I work on machine learning for particle physics with the CMS experiment at the Large Hadron Collider, ' +
    'through the EPN group. Two lines of work: a compact ParticleTransformer-inspired classifier (MiniParT) ' +
    'that separates H→bb, H→cc and QCD multijet events on CMS Open Data, and a replication of the CMS search ' +
    'for dark matter produced in association with a top quark at √s = 13 TeV.',
  links: [
    { label: 'MiniParT — jet flavour tagging', url: 'https://github.com/CMS-EPN/minipart-topology-vs-flavor' },
    { label: 'Dark matter search — paper replication', url: 'https://github.com/CMS-EPN/search-for-dark-matter-docs' },
    { label: 'CMS-EPN on GitHub', url: 'https://github.com/CMS-EPN' },
  ],
};

export const education = [
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.svg',
    title: 'BSc Computer Science',
    period: 'Nov 2023 — present',
    note: "Ecuador's leading engineering university. Algorithms, data structures, operating systems, numerical methods.",
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: 'AI Engineering Professional Certificate',
    period: '2023',
    note: 'Deep learning with Keras, TensorFlow and PyTorch; computer vision; neural networks.',
    href: 'https://coursera.org/share/770b0e12af6b0e1391e7f09c49f3610a',
  },
  {
    institution: 'IBM',
    logo: '/logos/ibm.svg',
    title: 'Data Science Professional Certificate',
    period: '2023',
    note: 'Python, SQL, data analysis and visualization, machine learning.',
    href: 'https://coursera.org/share/ce10faea4e3ca0a66209020b00cb7a60',
  },
  {
    institution: 'Escuela Politécnica Nacional',
    logo: '/logos/epn.svg',
    title: 'Data Science Diploma',
    period: '2023',
    note: 'Statistical analysis, machine learning, data visualization.',
    href: 'https://aps.cec-epn.edu.ec/diplomas/2023/CAPACITACION_Y_CONSULTORIA/6/diploma_190908_53970-signed.pdf',
  },
];

/** Professional experience, transcribed from Dax's CV. */
export const experience = [
  {
    role: 'CMS Collaborator',
    org: 'CERN — CMS Experiment',
    logo: '/logos/cms.png',
    period: 'May 2025 — present',
    note: 'Associate contributor to the CMS experiment, working on research reproducibility and modern software architectures for large-scale scientific computing.',
    points: [
      'Reproduced an antimatter physics research paper with the Data Preservation and Open Access (DPOA) group, focusing on reproducibility, data integrity and experiment validation.',
      'Designed and proposed modern software architectures for the BRIL group, supporting the CERN Phase-2 upgrades.',
      'Evaluated containerised, workflow-based solutions using Docker and Apache Airflow for scalable research pipelines.',
    ],
  },
  {
    role: 'Research Assistant',
    org: 'ADA Data Science Laboratory',
    logo: '/logos/epn.svg',
    period: 'Mar 2025 — present',
    note: 'Applied machine learning research and optimization algorithms.',
    points: [
      'Conducted applied research on machine learning optimization methods, including second-order optimizers.',
      'Designed and implemented Python experimental pipelines for model training, evaluation and benchmarking.',
      'Co-authored a research paper on second-order optimization methods for AI models.',
    ],
  },
  {
    role: 'AI Developer & Linux Systems Integrator',
    org: 'WORB',
    period: 'Apr 2025 — Dec 2025',
    note: 'Full-stack development integrating AI into production workflows and applications.',
    points: [
      'Backend architecture design, development and integration.',
      'AI embedding search and LLM integration.',
      'Database design and integration, plus frontend development.',
    ],
  },
];

/**
 * Grouped, not rated. Self-assigned 1–5 levels invite an argument you cannot win and tell
 * a reader nothing the projects don't already prove.
 */
export const skills = [
  { group: 'Languages', items: ['Python', 'Rust', 'C', 'C++', 'Java', 'TypeScript', 'Bash', 'SQL'] },
  { group: 'Systems & Linux', items: ['Linux', 'PAM', 'Syscalls', 'Sockets', 'Docker', 'Nginx', 'Kubernetes'] },
  { group: 'Networks & Security', items: ['TCP/IP', 'Network Engineering', 'Wireshark', 'Keycloak', 'OAuth2'] },
  { group: 'ML & Data', items: ['PyTorch', 'TensorFlow', 'scikit-learn', 'ONNX', 'OpenCV', 'NumPy', 'Pandas'] },
  { group: 'Backend', items: ['FastAPI', 'Django', 'Spring Boot', 'PostgreSQL', 'Redis', 'REST'] },
  { group: 'Physics & Numerics', items: ['ROOT', 'NanoAOD', 'Numerical Methods', 'SciPy', 'Manim'] },
];
